# Домашнее задание "Линейная алгебра. Матрицы".

## Уровень 0:


### Задание 1

 - Создайте матрицу 3 на 3, заполненную числами от 1 до 9
 - Прибавьте к ней матрицу с единицами на диагонале
 - Умножьте полученную матрицу на вектор (1, 2, 3)
 - Вычислить транспонированную матрицу $A^T$ от полученной в результате прибавления матрицы
 - Посчитайте обратную матрицу к полученной в результате прибавления матрице


In [1]:
import numpy as np

In [15]:
A1 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
A2 = np.eye(3)

In [16]:
A3 = A1 + A2
A3

array([[ 2.,  2.,  3.],
       [ 4.,  6.,  6.],
       [ 7.,  8., 10.]])

In [20]:
A4 = ([1, 2, 3])
A5 = A3@A4
A5

array([15., 34., 53.])

In [23]:
A6 = (A3).T
A6

array([[ 2.,  4.,  7.],
       [ 2.,  6.,  8.],
       [ 3.,  6., 10.]])

In [24]:
A7 = np.linalg.inv(A3)
A7

array([[-6. , -2. ,  3. ],
       [-1. ,  0.5,  0. ],
       [ 5. ,  1. , -2. ]])

## Уровень 1:

### Задание 2

Найдите собственные значения и собственные вектора матрицы:
```
m = np.array([[2, 2],
              [1, 3]])
print(m)
```



In [26]:
m = np.array([[2, 2], [1, 3]])
m

array([[2, 2],
       [1, 3]])

In [37]:
v = np.linalg.eig(m)
print(f"Собственные значения: {v[0][0]} и {v[0][1]}\nСобственные векторы: {v[1][0]} и {v[1][1]}")

Собственные значения: 1.0 и 4.0
Собственные векторы: [-0.89442719 -0.70710678] и [ 0.4472136  -0.70710678]


### Задание 3


Придумайте матрицу, у которой определитель = 1, и все элементы не равны 0.

P.S. Матрица должна быть ненулевой и размерностью не менее 2! 

In [209]:
matrix = np.array([[3, 2, 2], 
                   [2, 3, 2], 
                   [5, 2, 3]])

In [210]:
np.linalg.det(matrix)

1.0000000000000018